### PR TITLE
Fix some Spanish name conjunctions

### PR DESCRIPTION
**Pull request by bobjflong**

### CODE REVIEW

**Comment by bobjflong** [comment]
thanks @tenderlove

**Comment by aprescott** [comment]
I think this breaks the test suite, because `options[:spanish]` isn't specified in the tests.

```
TestNameCase#test_namecase [test/test_namecase.rb:34]:
Expected: "Ruiz y Picasso"
  Actual: "Ruiz Y Picasso"
```

**Comment by aprescott** [comment]
Although I see that `spanish: true` is a default in `lib/namecase.rb`... But still, failing tests on `master`.

**Comment by bobjflong** [comment]
@aprescott that's weird. Are you 100% sure you're running latest master? You should see this stuff in `namecase.rb`: 

```ruby
    if options[:spanish]
      ["Y", "E", "I"].each do |conjunction|
        localstring.gsub!(/\b#{conjunction}\b/, conjunction.downcase)
      end
    end
```

FWIW I just pulled from master, and had to fixup the test class to be:

```ruby
class TestNameCase < Minitest::Unit::TestCase
```

And I get a clean test run:

```
namecase ➤ bundle exec rake                                                                                          git:master*
/Users/bob/.rbenv/versions/2.1.6/bin/ruby -w -Ilib:bin:test:. -e 'require "rubygems"; require "minitest/autorun"; require "test/test_namecase.rb"' -- 
Run options: --seed 48372

# Running tests:

...

Finished tests in 0.007776s, 385.8025 tests/s, 24305.5556 assertions/s.

3 tests, 189 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by aprescott** [comment]
Hm, I think you might be right. I think the test might have been using a previously installed gem instead of what's in `lib/` (by adding `lib/` to `$LOAD_PATH` instead of doing `require "rubygems"`). I had problems running it with `bundle exec rake` so I was doing `ruby test/test_namecase.rb`. Guess it's fine!

**Pull request merged**
